// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fqlkmzaptmnuazogiznq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZxbGttemFwdG1udWF6b2dpem5xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4MjMxMDAsImV4cCI6MjA2NDM5OTEwMH0.IZ_BGrZpz4gu7xJpNNhuP9QI-_nP-a1aQsDAYDpFqcM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);